title: vsubs
email: email@vsubs.ru
description: |
  Coding and shitposting!
baseurl: "" # the subpath of your site, e.g. /blog
url: "vsubhuman.com"
github_username:  vsubhuman

theme: jekyll-theme-tactile
permalink: /:title
